version: '3.8'
services:
  rock_paper_db:
    container_name: rock_paper_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - application

  rock_paper_api:
    container_name: rock_paper_api
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rock_paper_db
    networks:
      - application
networks:
  application:
    name: 'application'
    driver: bridge
