version: "3.2"
services:
  postgres-salinity-prod:
    container_name: postgres-salinity-prod
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/production/salinity/data/postgres-data:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    networks:
      - salinity-network

networks:
  salinity-network:
    driver: bridge
